Repository Parabot/Randoms, pull requests merged in 2018-11, with the labels that each got.

#62 [FEATURE]Added OSWar pick item random event
  src/main/java/org/parabot/randoms/Core.java
  src/main/java/org/parabot/randoms/oswar/ItemPicker.java
Labels: priority:low, status:accepted, type:feature

#64 [TASK] Bumped to version 0.26.1
  .travis.yml
  pom.xml
Labels: priority:low, status:accepted, type:improvement

#63 [MERGE] Development into master
  .travis.yml
  pom.xml
  src/main/java/org/parabot/randoms/Core.java
  src/main/java/org/parabot/randoms/oswar/ItemPicker.java
  src/main/java/org/parabot/randoms/runewild/MacAddressFix.java
Labels: priority:low, status:accepted, type:feature, type:improvement
